config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/' => 'orders#new'
  get 'modal' => 'orders#modal', as: :modal
  post 'phone_order' => 'orders#phone_order', as: :phone_order
  resources :orders do
    post 'send_mail'
  end
  root to: 'orders#new'
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  validates :phone, presence: true
  validates_format_of :email,
                      with: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :from, presence: true
  validates :to, presence: true
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :set_order, only: %i[show]

  # GET /orders/new
  def new
    @order = Order.new
  end

  def show
    @text = 'Точную цену для вашего запроса уточняйте у менеджера'
  end

  def create
    if @text.blank?
      if order_params[:weight].to_i <= 600
        lightwieght(order_params)
      elsif order_params[:weight].to_i <= 2000 && order_params[:volume].to_i <= 15
        heavywieght(order_params)
      end
    end
    @order = Order.new(order_params)
    @order.price = @price
    @order.car_enabled = if @car
                           true
                         else
                           false
                         end
    if @order.save
      redirect_to order_path(@order)
    else
      redirect_to root_path
    end
  end

  def send_mail
    @order = Order.find(params[:order_id])
    OrderMailer.send_email(@order).deliver
    flash[:notice] = 'Наш менеджер перезвонит вам через 10 минут!'
    redirect_to root_path
  end

  def modal
    @phone = ''
    respond_to do |format|
      format.html
      format.js
    end
  end

  def phone_order
    OrderMailer.phone_order(params).deliver
    flash[:notice] = 'Наш менеджер перезвонит вам через 10 минут!'
    redirect_to root_path, notice: 'Наш менеджер перезвонит вам через 10 минут!'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    pallet(params) if params[:order][:pallett]
    if session[:pallet].nil?
      if params[:order][:height] && params[:order][:weight] && params[:order][:length]
        sum_volume(params)
      end
      if params[:order][:to].eql?(params[:order][:from]) || params[:order][:to].eql?('Другой город') || params[:order][:from].eql?('Другой город')
        intown(params)
      end
      car(params) if params[:order][:car].present?
    end
    session[:pallet] = nil
    params.require(:order).permit(:name, :surname, :from, :to, :email, :phone, :weight, :volume, :date)
  end

  def pallet(params)
    params[:order][:volume] = (params[:order][:pallett].to_i * 2).to_s
    @price = 4000 if params[:order][:weight].to_i < 100
    session[:pallet] = true
  end

  def sum_volume(params)
    params[:order][:volume] = (params[:order][:height].to_f * params[:order][:width].to_f * params[:order][:length].to_f).to_i.round.to_s
  end

  def intown(_params)
    @price = 0
    @text = 'Точную цену для вашего запроса уточняйте у менеджера'
  end

  def car(params)
    case params[:order][:car]
    when 'Машина до 2 тонн, максимум 16 метров кубических'
      params[:order][:weight] = 2000
      params[:order][:volume] = 16
      @price = 20_000
    when 'Машина до 3 тонн, максимум 20 метров кубических'
      params[:order][:weight] = 3000
      params[:order][:volume] = 20
      @price = 24_000
    when 'Машина до 5 тонн, максимум 35 метров кубических'
      params[:order][:weight] = 5000
      params[:order][:volume] = 35
      @price = 27_000
    end
    @car = true
  end

  def lightwieght(order_params)
    @price = if order_params[:weight].to_i == 100 && order_params[:volume].to_i == 1
               4000
             elsif order_params[:weight].to_i == 200 && order_params[:volume].to_i == 1
               4300
             elsif order_params[:weight].to_i == 300 && order_params[:volume].to_i == 1
               4700
             elsif order_params[:weight].to_i == 400 && order_params[:volume].to_i == 1
               5000
             elsif order_params[:weight].to_i == 500 && order_params[:volume].to_i == 1
               5300
             elsif order_params[:weight].to_i == 200 && order_params[:volume].to_i == 1
               5800
             elsif order_params[:weight].to_i == 100 && order_params[:volume].to_i == 2
               4300
             elsif order_params[:weight].to_i == 200 && order_params[:volume].to_i == 2
               4700
             elsif order_params[:weight].to_i == 300 && order_params[:volume].to_i == 2
               5000
             elsif order_params[:weight].to_i == 400 && order_params[:volume].to_i == 2
               5300
             elsif order_params[:weight].to_i == 500 && order_params[:volume].to_i == 2
               5800
             elsif order_params[:weight].to_i == 600 && order_params[:volume].to_i == 2
               6300
             elsif order_params[:weight].to_i == 100 && order_params[:volume].to_i == 3
               4800
             elsif order_params[:weight].to_i == 200 && order_params[:volume].to_i == 3
               5100
             elsif order_params[:weight].to_i == 300 && order_params[:volume].to_i == 3
               5500
             elsif order_params[:weight].to_i == 400 && order_params[:volume].to_i == 3
               5800
             elsif order_params[:weight].to_i == 500 && order_params[:volume].to_i == 3
               6200
             elsif order_params[:weight].to_i == 600 && order_params[:volume].to_i == 3
               6600
             elsif order_params[:weight].to_i == 100 && order_params[:volume].to_i == 4
               5700
             elsif order_params[:weight].to_i == 200 && order_params[:volume].to_i == 4
               6000
             elsif order_params[:weight].to_i == 300 && order_params[:volume].to_i == 4
               6400
             elsif order_params[:weight].to_i == 400 && order_params[:volume].to_i == 4
               6800
             elsif order_params[:weight].to_i == 500 && order_params[:volume].to_i == 4
               7100
             elsif order_params[:weight].to_i == 600 && order_params[:volume].to_i == 4
               7500
             elsif order_params[:weight].to_i == 100 && order_params[:volume].to_i == 5
               6500
             elsif order_params[:weight].to_i == 200 && order_params[:volume].to_i == 5
               6900
             elsif order_params[:weight].to_i == 300 && order_params[:volume].to_i == 5
               7300
             elsif order_params[:weight].to_i == 400 && order_params[:volume].to_i == 5
               7800
             elsif order_params[:weight].to_i == 500 && order_params[:volume].to_i == 5
               8100
             elsif order_params[:weight].to_i == 600 && order_params[:volume].to_i == 5
               8400
             elsif order_params[:weight].to_i == 100 && order_params[:volume].to_i == 6
               7000
             elsif order_params[:weight].to_i == 200 && order_params[:volume].to_i == 6
               7700
             elsif order_params[:weight].to_i == 300 && order_params[:volume].to_i == 6
               8000
             elsif order_params[:weight].to_i == 400 && order_params[:volume].to_i == 6
               8300
             elsif order_params[:weight].to_i == 500 && order_params[:volume].to_i == 6
               8700
             elsif order_params[:weight].to_i == 600 && order_params[:volume].to_i == 6
               9000
             elsif order_params[:weight].to_i == 100 && order_params[:volume].to_i == 7
               7500
             elsif order_params[:weight].to_i == 200 && order_params[:volume].to_i == 7
               8000
             elsif order_params[:weight].to_i == 300 && order_params[:volume].to_i == 7
               8400
             elsif order_params[:weight].to_i == 400 && order_params[:volume].to_i == 7
               8800
             elsif order_params[:weight].to_i == 500 && order_params[:volume].to_i == 7
               9200
             elsif order_params[:weight].to_i == 600 && order_params[:volume].to_i == 7
               9500
             else
               0
             end
    if @price == 0
      @text = 'Точную цену для вашего запроса уточняйте у менеджера'
    end
    end

  def heavywieght(order_params)
    weight = order_params[:weight].to_i
    volume = order_params[:volume].to_i
    @price = if Range.new(700, 899).include?(weight) && Range.new(1, 2).include?(volume)
               6000
             elsif Range.new(700, 899).include?(weight) && Range.new(3, 4).include?(volume)
               7500
             elsif Range.new(700, 899).include?(weight) && Range.new(5, 6).include?(volume)
               8000
             elsif Range.new(700, 899).include?(weight) && Range.new(7, 8).include?(volume)
               9500
             elsif Range.new(700, 899).include?(weight) && Range.new(9, 10).include?(volume)
               10_000
             elsif Range.new(700, 899).include?(weight) && Range.new(10, 12).include?(volume)
               11_000
             elsif Range.new(700, 899).include?(weight) && Range.new(12, 14).include?(volume)
               12_000
             elsif Range.new(700, 899).include?(weight) && Range.new(15, 16).include?(volume)
               13_000
             elsif Range.new(900, 1099).include?(weight) && Range.new(1, 2).include?(volume)
               7500
             elsif Range.new(900, 1099).include?(weight) && Range.new(3, 4).include?(volume)
               8000
             elsif Range.new(900, 1099).include?(weight) && Range.new(5, 6).include?(volume)
               9500
             elsif Range.new(900, 1099).include?(weight) && Range.new(7, 8).include?(volume)
               10_000
             elsif Range.new(900, 1099).include?(weight) && Range.new(9, 10).include?(volume)
               11_000
             elsif Range.new(900, 1099).include?(weight) && Range.new(11, 12).include?(volume)
               11_000
             elsif Range.new(900, 1099).include?(weight) && Range.new(13, 14).include?(volume)
               12_000
             elsif Range.new(900, 1099).include?(weight) && Range.new(15, 16).include?(volume)
               13_000
             elsif Range.new(1100, 1299).include?(weight) && Range.new(1, 2).include?(volume)
               7500

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_modal.html.erb
<div class="modal-header">
  <h4 style="color:black !important;padding-left:100px" class="modal-title" id="myModalLabel">Связаться с менеджером</h4>
</div>
<div class="modal-body">
  <%= form_for(@phone, url: phone_order_path, method: :post, remote: :true) do |form| %>
  <div class="col-lg-12">
    <div class="form-group">
      <%= form.label :Имя %><sup>*</sup>
      <%= form.text_field :first_name, required: true, class: "form-control", placeholder: "Имя", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'Имя'" %>
      <%= form.label :Фамилия %>
      <%= form.text_field :last_name, class: "form-control", placeholder: "Фамилия", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'Фамилия'" %>
      <%= form.label :Телефон %><sup>*</sup>
      <%= form.phone_field :phone, required: true, class: "form-control", placeholder: "Телефон", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'Телефон'" %>
    </div>
    </div>
    <%= button_to 'Отправить заявку', phone_order_path, method: :post, class: 'main_btn mt-md-0 mt-4', style: 'margin-left:15px;' %>
    <% end %>
</div>
<div class="modal-footer">

</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/modal.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'modal') %>");
$("#modal-window").modal();

app/views/orders/show.html.erb
<!--================ Start Quote Area =================-->
<% content_for :head do %>
  <meta name="robots" content="noindex, nofollow" />
  <meta name="googlebot" content="noindex" />
<% end %>
<section style="margin-top:50px" class="quote-area">
  <div class="container">
    <div class="row justify-content-between align-items-center">
      <div class="col-lg-12">
       <div class="card">
         <div class="jumbotron card card-image" style="background-color: whitesmoke; no-repeat center;padding:0;margin-bottom:0">
           <div class="text-white text-center py-5 px-4">
             <div>
               <h2 style="color: black !important"class="card-title h1-responsive pt-3 mb-5 font-bold"><strong>Ваш заказ</strong></h2>
               <% if @order.price.nil? || @order.price == 0  %>
                 <p style="color:black !important;" class="lead"><strong><%= @text %></strong></p>
               <% else %>
                 <h5 style="color: black;">Предварительная цена:</h5><p class="lead" style="color:black !important;font-size:18px;font-style:bold"><strong><%= @order.price %> рублей</strong></p>
                 <h5 style="color: black;">Со скидкой 10% на первый заказ</h5><p class="lead" style="color:black !important;font-size:18px;font-style:bold"><strong><%= (@order.price*0.9).to_i %> рублей</strong></p>
                 <div class="form-group">
                   <strong>
                     <% if @order.car_enabled == true %>
                       Да
                     <% else %>
                       Нет
                     <% end %>
                   </strong></p>
                 </div>
               <% end %>
               <hr class="my-4">
               <div class="row">
                 <div class="col-lg-3">
                   <div class="form-group">
                     <h6 style="margin-bottom:0;color: black;">Имя:</h6>
                     <p style="color:black !important;font-size:14px"><strong><%= @order.name %></strong></p>
                   </div>
                 </div>
                 <div class="col-lg-3">
                   <div class="form-group">
                     <h6 style="color: black;margin-bottom:0">Фамилия:</h6><p class="card-text" style="color:black !important;font-size:14px"><strong><%= @order.surname %></strong></p>
                   </div>
                 </div>
                 <div class="col-lg-3">
                   <div class="form-group">
                     <h6 style="color: black;margin-bottom:0">E-mail:</h6><p class="card-text" style="color:black !important;font-size:14px"><strong><%= @order.email %></strong></p>
                   </div>
                 </div>
                 <div class="col-lg-3">
                   <div class="form-group">
                     <h6 style="color: black;margin-bottom:0">Телефон:</h6><p class="card-text" style="color:black !important;font-size:14px"><strong><%= @order.phone %></strong></p>
                   </div>
                 </div>
                 <div class="col-lg-3">
                   <div class="form-group">
                     <h6 style="color: black;margin-bottom:0">Откуда:</h6><p class="card-text" style="color:black !important;font-size:14px"><strong><%= @order.from %></strong></p>
                   </div>
                 </div>
                 <div class="col-lg-3">
                   <div class="form-group">
                     <h6 style="color: black;margin-bottom:0">Куда:</h6><p class="card-text" style="color:black !important;font-size:14px"><strong><%= @order.to %></strong></p>
                   </div>
                 </div>
                 <div class="col-lg-3">
                   <div class="form-group">
                     <h6 style="color: black;margin-bottom:0">Вес:</h6><p class="card-text" style="color:black !important;font-size:14px"><strong><%= @order.weight %> кг</strong></p>
                   </div>
                 </div>
                 <div class="col-lg-3">
                   <div class="form-group">
                     <h6 style="color: black;margin-bottom:0">Объем:</h6><p class="card-text" style="color:black !important;font-size:14px"><strong><%= @order.volume %> куб.м.</strong></p>
                   </div>
                 </div>
               </div>
             </div>
             <%= button_to 'Отправить заявку', order_send_mail_path(@order), class: "btn btn-success btn-rounded mb-4", style: "margin-top:20px" %>
             <%= link_to 'Вернуться на главную', root_path, class: "btn btn-success btn-rounded mb-4", style: "margin-top:20px;border:1px solid black !important;color:black" %>
           </div>
         </div>
       </div>
</section>
<!--================ End Quote Area =================-->
<!--================ Feature Area =================-->
<section style="background-color:#070475" class="feature-area section_gap_top">
  <div class="container">
    <div class="row align-items-center justify-content-center">
      <div class="col-lg-7">
        <div class="row">
          <div class="col-lg-4 col-md-4">
            <div class="single-feature">
              <%= image_tag "feature/f1.png", class: "lazy" %>
              <h4>Скорость доставки</h4>
              <p>
                Груз будет доставлен на следующий день после погрузки. В случае заказа отдельной машины, доставим груз
                в течении 12 часов.
              </p>
            </div>
          </div>
          <div class="col-lg-4 col-md-4">
            <div class="single-feature">
              <%= image_tag "feature/f2.png", class: "lazy" %>
              <h4>Погрузка</h4>
              <p>
                При необходимости предоставим необходимое количество грузчиков в место погрузки или выгрузки.
              </p>
            </div>
          </div>
          <div class="col-lg-4 col-md-4">
            <div class="single-feature">
              <%= image_tag "feature/f5.png", class: "lazy" %>
              <h4>Упаковка</h4>
              <p>
                Профессионально выполненная упаковка и верно подобранные упаковочные материалы защитят груз от повреждений.
              </p>
            </div>
          </div>
          <div class="col-lg-4 col-md-4">
            <div class="single-feature">
              <%= image_tag "feature/f6.png", class: "lazy" %>
              <h4>Страховка</h4>
              <p>
                Мы предлагаем клиентам выгодные условия страхования грузов на все время перевозки, независимо от грузов.
              </p>
            </div>
          </div>
          <div class="col-lg-4 col-md-4">
            <div class="single-feature">
              <%= image_tag "feature/f3.png", class: "lazy" %>
              <h4>Ценовая политика</h4>
              <p>
                Наши цены самые низкие. В цену уже включены забор груза у отправителя и доставка по нужному адресу получателю.
              </p>
            </div>
          </div>
          <div class="col-lg-4 col-md-4">
            <div class="single-feature">
              <%= image_tag "feature/f4.png", class: "lazy" %>
              <h4>Buisness to buisness</h4>
              <p>
                Заключаем долгосрочные договора с оплатой по безналичному расчету, с отсрочкой платежа.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-5 offset-md-0 col-md-12 text-left section-title-wrap mt-4 mt-lg-0">
        <h3>
          Грузоперевозки между Москвой
          и Санкт-Петербургом <br>
          Выбор очевиден.
        </h3>
        <h4></h4>
        <p>
          Мы осуществляем грузоперевозки автомобильным транспортом: между Санкт-Петербургом и Москвой,
          доставляем по всей Центральной части России <br><br>
          Мы используем разнообразный автотранспорт грузоподъёмностью до 5 тонн, с различными объемами  кузова<br><br> Мы производим перевозки грузов исключительно за
          счет собственных ресурсов, без перегрузов, и терминального хранения(door-to-door)! <br><br> Мы можем
          гарантировать исключительное качество наших услуг – доставку груза на следующий день в удобное для Вас время и
          сохранность Вашего отправления!
        </p>
      </div>
    </div>
  </div>
</section>
<!--================ End Feature Area =================-->
<!--================ About Area =================-->
<section class="about-area" style="margin-top:50px">
  <section class="about-area" style="margin-top:50px">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="row justify-content-center text-left section-title-wrap">
            <div class="col-lg-12">
              <h2>
                Наши партнеры
              </h2>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-10">
              <div class="row">
                <div class="col-lg-4 col-md-4 col-6 single_brand">
                  <%= image_tag "about/brand1.png", class: "lazy" %>
                </div>
                <div class="col-lg-4 col-md-4 col-6 single_brand">
                  <%= image_tag "about/brand2.png", class: "lazy" %>
                </div>
                <div class="col-lg-4 col-md-4 col-6 single_brand">
                  <%= image_tag "about/brand3.png", class: "lazy" %>
                </div>
                <div class="col-lg-4 col-md-4 col-6 single_brand">
                  <%= image_tag "about/brand4.png", class: "lazy" %>
                </div>
                <div class="col-lg-4 col-md-4 col-6 single_brand">
                  <%= image_tag "about/brand5.png", class: "lazy" %>
                </div>
                <div class="col-lg-4 col-md-4 col-6 single_brand">
                  <%= image_tag "about/brand6.png", class: "lazy" %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-3" style="margin-top:120px">
          <div style="margin-top:60px;" class="about_box">
            <div class="activity">
              <div class="col-lg-12 col-md-12 col-12 text-center">
                <div class="activity_box">
                  <div>
                    <%= image_tag "about/i1.png", class: "lazy" %>
                    <h3><span class="counter">25000</span>+</h3>
                    <p>Грузов доставлено</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<!--================ End About Area =================-->
<!--================ Start CTA Area ================-->
<section class="cta_area">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="cta_inner d-flex flex-md-row flex-column justify-content-between align-items-center">
          <div class="mb-md-0 mb-4 text-sm-left text-center col-lg-8 col-sm-8 col-md-8">
            <p>Хотите узнать подробнее?</p>
            <h1 style="font-size:30px">Закажите звонок и мы перезвоним вам в течении 10 минут</h1>
          </div>
          <div class="mb-md-0 mb-4 text-sm-left text-center col-lg-8 col-sm-8 col-md-8">
            <%= link_to 'Заказать', modal_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'main_btn', style:'width:100%'}  %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
</section>
<!--================ End CTA Area ================-->